application: functiongrapher
version: 0
api_version: 1
runtime: python

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /valid-xhtml11-mathml20-svg11-blue.png
  static_files: valid-xhtml11-mathml20-svg11-blue.png
  upload: valid-xhtml11-mathml20-svg11-blue.png

- url: .*
  script: main.py
